name: Java Application

on:
  push:
    branches:
      - master  # or the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@<commit-sha>
      with:
        jenkins_url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: 'your-jenkins-job-name'
      
    - name: Wait for Jenkins Job to Complete
      uses: appleboy/jenkins-action@<commit-sha>
      with:
        jenkins_url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: 'your-jenkins-job-name'
        wait: true
